import fs from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
const html=fs.readFileSync(new URL('../index.html',import.meta.url),'utf8');
for(const m of html.matchAll(/<script\b[^>]*>([\s\S]*?)<\/script>/gi))new vm.Script(m[1]);
const art=fs.readFileSync(new URL('../art/scenery.js',import.meta.url),'utf8');
const source=art.match(/function neoOrbit\([\s\S]*?\n}/)[0];
const orbit=vm.runInNewContext('('+source+')');
const dawn=orbit(6,6,1000,200),noon=orbit(12,6,1000,200),dusk=orbit(18,6,1000,200);
assert(Math.abs(dawn.y-200)<1e-8 && Math.abs(dusk.y-200)<1e-8);
assert(Math.abs(noon.x-500)<1e-8 && noon.y<dawn.y);
assert(dawn.x<noon.x && noon.x<dusk.x);
assert(!orbit(0,6,1000,200).visible);
assert(orbit(0,18,1000,200).visible);
assert(Math.abs(orbit(23.99999,18,1000,200).x-orbit(0,18,1000,200).x)<.01);
assert(!art.includes('destination-out'));
console.log('PASS: script parsing, horizon crossings, noon apex, direction, night visibility, midnight continuity, non-destructive moon rendering.');
const depthSource=art.match(/function neoCatDepth\([\s\S]*?\n}/)[0];
const depth=vm.runInNewContext('('+depthSource+')',{decor:[{type:'station',station:'bakery',y:300}]});
const cottage=200;
assert(depth({state:'walking',y:180})<cottage);
assert(depth({state:'walking',y:220})>cottage);
assert(depth({state:'indoors',y:199,_cotY:cottage})>cottage);
assert(depth({state:'indoors',y:48,_cotY:200,_perchKind:'perch'})>191);
assert(depth({state:'indoors',y:48,_cotY:200,_perchKind:'perch'})<depth({state:'walking',y:205}));
assert(depth({state:'baking',y:280,_station:'bakery'})>300);
console.log('PASS: behind/in-front order, cottage doorway, elevated perch, and working-station depth.');
const lightSource=art.match(/function neoLight\([\s\S]*?\n}/)[0];
const light=vm.runInNewContext('('+lightSource+')');
assert(light(0).night>light(21).night && light(21).night>light(18).night);
assert(light(6).twilight>light(12).twilight && light(18).twilight>light(0).twilight);
const ridge=JSON.parse(art.match(/const NEO_SKYLINE=(\[[^;]+\]);/)[1]);
function ridgeAt(x){for(let i=1;i<ridge.length;i++){if(x<=ridge[i][0]){const a=ridge[i-1],b=ridge[i];return a[1]+(b[1]-a[1])*(x-a[0])/(b[0]-a[0]);}}return ridge.at(-1)[1];}
const rising=orbit(6,6,1536,300),setting=orbit(18,6,1536,300),high=orbit(12,6,1536,300);
assert(rising.y>ridgeAt(rising.x) && setting.y>ridgeAt(setting.x));
assert(high.y<ridgeAt(high.x));
console.log('PASS: mountain occlusion geometry, twilight timing, and deepest night at moon apex.');
const cloudSource=art.match(/function neoCloudPose\([\s\S]*?\n}/)[0];
const cloudPose=vm.runInNewContext('('+cloudSource+')');
for(let i=0;i<4;i++){
 const a=cloudPose(i,10,1200,300,100),b=cloudPose(i,11,1200,300,100);
 assert(b.x>a.x && b.x-a.x<4);assert.equal(a.y,b.y);assert.equal(a.s,b.s);
}
assert(art.includes('if(!art2dStill)neoCloudTime+='));
assert(art.includes('neoMovingClouds(g,w,hz,over);'));
console.log('PASS: steady slow cloud drift, fixed height/scale, reduced-motion guard and render integration.');
