import fs from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
const html=fs.readFileSync(new URL('../index.html',import.meta.url),'utf8');
const fn=n=>html.match(new RegExp('function '+n+'\\([^]*?^}', 'm'))[0];
const background=vm.runInNewContext('('+fn('backgroundShells')+')');
assert.equal(background(1,0),0);
assert.equal(background(1,-1),0);
assert.equal(background(1,14400),2592);
assert.equal(background(1,28800),3240);
assert.equal(background(1,86400),background(1,43200));
assert(background(1,28800)-background(1,14400)<background(1,14400));
const rateCode=html.match(/  ratePerSec\(\) \{[^]*?\n  \}/)[0].replace('ratePerSec()', 'function ratePerSec()');
let n=3;
const rate=vm.runInNewContext('('+rateCode+')',{earnMult:()=>.46,residentCount:()=>n,comfortMult:()=>1,STATION:{},clamp:(x,a,b)=>Math.max(a,Math.min(b,x))});
const cat={traitRate:()=>1,moodMul:()=>1.2,star:1,growth:1,state:'loafing',hunger:0,thirst:0};
let last=0;
for(n of [3,8,16,24]){const perHour=rate.call(cat)*n*3600;assert(perHour>last);last=perHour;console.log(`${n} cats: ${Math.round(perHour)} shells/hour, tree ${Math.round(300/perHour*60)} minutes`);}
n=3;assert(300/(rate.call(cat)*3*60)>30);assert(300/(rate.call(cat)*3*60)<45);
const ctx={G:{shells:0},document:{hidden:false,getElementById:()=>({hidden:true})},aggregateRate:()=>1,goalShells:()=>100,festPlaySeconds:0,festBank:0,festKind:'cafe',racePhase:'picker',boxPhase:'idle',volleyPhase:'idle',midkPhase:'idle',_cafeRunning:true};
vm.createContext(ctx);vm.runInContext(fn('festivalEconomyStep')+'\n'+fn('balanceFestivalReward'),ctx);
vm.runInContext('for(let i=0;i<1440;i++)festivalEconomyStep(.1)',ctx);
assert(Math.abs(ctx.G.shells-144)<=1);
const rw=vm.runInContext('balanceFestivalReward({shells:100})',ctx);
assert.equal(rw.shells,58);assert.equal(ctx.festPlaySeconds,0);
ctx.document.hidden=true;const bank=ctx.G.shells;vm.runInContext('festivalEconomyStep(60)',ctx);assert.equal(ctx.G.shells,bank);
assert(html.includes('driftTimer = rand(360, 600)'));
assert(html.includes('short: 18, day: 110, night: 190'));
assert(18/.5>110/4 && 110/4>190/8);
console.log('PASS: collection growth, early purchase target, background tail/cap, Festival base plus skill bonus, hidden-page protection and adventure hourly ordering.');
