import fs from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
const html=fs.readFileSync(new URL('../index.html',import.meta.url),'utf8');
for(const m of html.matchAll(/<script\b[^>]*>([\s\S]*?)<\/script>/gi))new vm.Script(m[1]);
const art=fs.readFileSync(new URL('../art/scenery.js',import.meta.url),'utf8');
const source=art.match(/function neoOrbit\([\s\S]*?\n}/)[0];
const orbit=vm.runInNewContext('('+source+')');
const dawn=orbit(6,6,1000,200),noon=orbit(12,6,1000,200),dusk=orbit(18,6,1000,200);
assert(Math.abs(dawn.y-200)<1e-8 && Math.abs(dusk.y-200)<1e-8);
assert(Math.abs(noon.x-500)<1e-8 && noon.y<dawn.y);
assert(dawn.x<noon.x && noon.x<dusk.x);
assert(!orbit(0,6,1000,200).visible);
assert(orbit(0,18,1000,200).visible);
assert(Math.abs(orbit(23.99999,18,1000,200).x-orbit(0,18,1000,200).x)<.01);
assert(!art.includes('destination-out'));
console.log('PASS: script parsing, horizon crossings, noon apex, direction, night visibility, midnight continuity, non-destructive moon rendering.');
const depthSource=art.match(/function neoCatDepth\([\s\S]*?\n}/)[0];
const depth=vm.runInNewContext('('+depthSource+')',{decor:[{type:'station',station:'bakery',y:300}]});
const cottage=200;
assert(depth({state:'walking',y:180})<cottage);
assert(depth({state:'walking',y:220})>cottage);
assert(depth({state:'indoors',y:199,_cotY:cottage})>cottage);
assert(depth({state:'indoors',y:48,_cotY:200,_perchKind:'perch'})>191);
assert(depth({state:'indoors',y:48,_cotY:200,_perchKind:'perch'})<depth({state:'walking',y:205}));
assert(depth({state:'baking',y:280,_station:'bakery'})>300);
console.log('PASS: behind/in-front order, cottage doorway, elevated perch, and working-station depth.');
