import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
await import('../ui/cafe-engine.js');
const actual=globalThis.CoveCafeEngine;
// Service regression fixtures represent established cafes with a menu.
const E={...actual,unlock(g,now){const ok=actual.unlock(g,now);if(ok){g.cafe.menu=actual.recipes.map(r=>r.id);g.cafe.discovered=[...g.cafe.menu];g.cafe.open=true;}return ok;}};
const beginner={shells:1000,homestead:{stock:{}}};actual.unlock(beginner,0);assert.equal(beginner.cafe.open,false);assert.equal(beginner.cafe.menu.length,0);actual.settle(beginner,999999);assert.equal(beginner.cafe.served,0);
const firstStock=beginner.homestead.stock.coffee;assert(actual.experiment(beginner,{coffee:1}).id);assert.equal(beginner.homestead.stock.coffee,firstStock-1);assert(beginner.cafe.discovered.includes('coffee'));assert.equal(beginner.cafe.menu.length,0);
const honeyBefore=beginner.homestead.stock.honey;assert(!actual.experiment(beginner,{honey:2}).id);assert.equal(beginner.homestead.stock.honey,honeyBefore-2);
const unchanged=JSON.stringify(beginner.homestead.stock);assert(actual.experiment(beginner,{honey:1}).error);assert.equal(JSON.stringify(beginner.homestead.stock),unchanged);assert(actual.experiment(beginner,{coffee:-1}).error);
console.log('PASS: closed empty-menu start, recipe discovery, tasting consumption, failure and insufficient-stock protection.');
const lessonStock=JSON.stringify(beginner.homestead.stock);assert.equal(actual.lesson(beginner).id,'coffee');assert.equal(JSON.stringify(beginner.homestead.stock),lessonStock);assert(actual.lesson(beginner).error);
assert(actual.nameRecipe(beginner,'coffee','  My   Cozy Cup  '));assert.equal(actual.displayName(beginner.cafe,actual.recipes[0]),'My Cozy Cup');assert(!actual.nameRecipe(beginner,'coffee','   '));
assert(!actual.improve(beginner,'coffee'));beginner.cafe.sales.coffee=10;const beforeUpgrade=beginner.shells;assert(actual.improve(beginner,'coffee'));assert.equal(beginner.shells,beforeUpgrade-50);assert.equal(actual.price(beginner.cafe,actual.recipes[0]),14);assert(!actual.improve(beginner,'coffee'));
actual.acquire(beginner,'carrot',3,2);actual.acquire(beginner,'honey',1,8);assert.equal(actual.experiment(beginner,{carrot:2,honey:1}).id,'bites');assert.equal(beginner.homestead.stock.carrot,1);assert(actual.nameRecipe(beginner,'bites','Garden Nibbles'));const restored=JSON.parse(JSON.stringify(beginner));assert.equal(restored.cafe.recipeNames.bites,'Garden Nibbles');assert.equal(restored.cafe.recipeLevels.coffee,1);
console.log('PASS: one free lesson, naming, food shared stock, recipe improvement gates/prices and save persistence.');
const finishGame={shells:10000,homestead:{stock:{}}};E.init(finishGame,0);E.unlock(finishGame,0);finishGame.shells=10000;
assert(E.buyFinish(finishGame,'butter'));assert.equal(finishGame.shells,7500);
assert(E.buyFinish(finishGame,'sage'));assert(E.buyFinish(finishGame,'butter'));assert.equal(finishGame.shells,7500);
const savedFinish=JSON.parse(JSON.stringify(finishGame));assert.equal(savedFinish.cafe.finish,'butter');assert(savedFinish.cafe.finishesOwned.includes('butter'));
finishGame.shells=1;assert(!E.buyFinish(finishGame,'rose'));assert.equal(finishGame.shells,1);assert.equal(finishGame.cafe.finish,'butter');assert(!E.buyFinish(finishGame,'missing'));
console.log('PASS: finish ownership, exact charge, free reuse, insufficient funds and save persistence.');
const make=()=>({shells:1000,homestead:{stock:{carrot:9},plots:[{key:'pumpkin',ready:555}],counter:4,earned:6,trays:[{key:'carrot',servings:4}],stoves:[{key:'berry',ready:999}],tables:4}});
let g=make(),legacy=JSON.stringify(g.homestead);E.init(g,0);assert(E.unlock(g,0));assert.equal(g.shells,918);assert.equal(g.homestead.counter,4);assert.equal(g.homestead.stoves[0].key,'berry');assert(!E.unlock(g,0));
g.cafe.cursor=0;E.settle(g,240000);assert.equal(g.cafe.served,0);assert(g.cafe.pending);assert.equal(g.homestead.stock.coffee,5);E.settle(g,270000);assert.equal(g.cafe.served,1);assert.equal(g.shells,930);E.settle(g,270000);assert.equal(g.shells,930);
g=JSON.parse(JSON.stringify(g));E.settle(g,269000);assert.equal(g.cafe.served,1);
let online=make(),offline=make();E.unlock(online,0);E.unlock(offline,0);for(let t=1000;t<=3600000;t+=1000)E.settle(online,t);E.settle(offline,3600000);assert.deepEqual(online,offline);
E.settle(offline,999999999);assert(Object.values(offline.homestead.stock).every(n=>n>=0));const paid=offline.shells;E.settle(offline,999999999);assert.equal(offline.shells,paid);
offline.cafe.open=false;E.settle(offline,1000999999);const stock=JSON.stringify(offline.homestead.stock);E.settle(offline,1001999999);assert.equal(JSON.stringify(offline.homestead.stock),stock);
let fresh=make();E.acquire(fresh,'coffee',10,50);assert.equal(fresh.cafe.basis.coffee,5);E.acquire(fresh,'coffee',10,10);assert.equal(fresh.cafe.basis.coffee,3);
let cap=make();E.unlock(cap,0);cap.homestead.stock={coffee:10000,catmint:10000,honey:10000};E.settle(cap,100*86400000);assert(cap.cafe.served<=180);
const html=fs.readFileSync(new URL('../index.html',import.meta.url),'utf8');for(const m of html.matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/g)){if(m[1].trim())new vm.Script(m[1]);}
assert(html.indexOf('ui/cafe-engine.js')<html.indexOf('function save()'));
console.log('PASS: unlock, legacy preservation, pending orders, no duplicate credits, save/reload, clock rollback, online/offline equivalence, stock limits, pause, weighted costs, offline cap and inline syntax.');
let shop=make();E.unlock(shop,0);shop.shells=49999;assert.equal(E.upgradeShop(shop,0),false);assert.equal(shop.shells,49999);
shop.shells=150000;const pantry=JSON.stringify(shop.homestead.stock);assert(E.upgradeShop(shop,0));assert.equal(shop.cafe.shopTier,1);assert.equal(shop.shells,100000);
shop=JSON.parse(JSON.stringify(shop));assert(E.upgradeShop(shop,0));assert.equal(shop.cafe.shopTier,2);assert.equal(shop.shells,0);assert.equal(JSON.stringify(shop.homestead.stock),pantry);assert.equal(E.upgradeShop(shop,0),false);
console.log('PASS: three sequential shop stages, exact 50k/100k costs, insufficient funds, final cap and save preservation.');
const reviews=make();E.unlock(reviews,0);E.settle(reviews,3600000);assert(reviews.cafe.customerReport.total>0);assert.equal(reviews.cafe.customerReport.total,reviews.cafe.served);assert(reviews.cafe.customerReport.happy<=reviews.cafe.customerReport.total);assert(reviews.cafe.feedbackLog.length<=10);assert(reviews.cafe.lastCompleted.response.text);const reportBefore=JSON.stringify(reviews.cafe.customerReport);E.settle(reviews,3600000);assert.equal(JSON.stringify(reviews.cafe.customerReport),reportBefore);assert.deepEqual(JSON.parse(JSON.stringify(reviews)).cafe.feedbackLog,reviews.cafe.feedbackLog);
console.log('PASS: completed-order feedback, bounded history, persistent happiness and no duplicate reviews.');
const supply={shells:1000,homestead:{stock:{coffee:4,honey:0},plots:[{key:'coffee',ready:Date.now()+900000}]}};actual.init(supply,0);supply.cafe.menu=['coffee','midknight'];const plan=actual.pantryPlan(supply),beans=plan.rows.find(r=>r.key==='coffee');assert.equal(beans.target,15);assert.equal(beans.growing,10);assert.equal(beans.plant,1);assert.equal(beans.patches,1);assert.equal(plan.rows.find(r=>r.key==='honey').target,5);assert.equal(plan.selected.find(r=>r.id==='midknight').orders,0);supply.homestead.plots[0].ready=0;assert.equal(actual.pantryPlan(supply).rows.find(r=>r.key==='coffee').ready,10);supply.cafe.menu=[];assert(actual.pantryPlan(supply).rows.every(r=>r.target===0));
console.log('PASS: shared recipe demand, growing/ready harvest credit, missing ingredient capacity and empty menu planning.');
const batch={shells:100,homestead:{stock:{},plots:[null,null]}};actual.init(batch,0);batch.cafe.menu=['coffee','midknight'];const quote=actual.plantingPlan(batch);assert.equal(quote.jobs.length,2);assert.equal(new Set(quote.jobs.map(j=>j.key)).size,2);const cash=batch.shells;assert(actual.plantSuggested(batch,quote,100));assert.equal(batch.shells,cash-quote.cost);assert(batch.homestead.plots.every(Boolean));assert(!actual.plantSuggested(batch,quote,100));batch.homestead.plots=[null,null];batch.shells=0;assert(!actual.plantSuggested(batch,actual.plantingPlan(batch),100));assert(batch.homestead.plots.every(p=>p===null));
console.log('PASS: recommended batch planting, cost, occupied plot protection and insufficient funds.');
