(function(root){
 'use strict';
 let stopActive=()=>{};
 root.CoveCafeView={open(a){
  stopActive();
  const E=root.CoveCafeEngine,g=a.game(),s=E.init(g,Date.now());a.close();
  let panel=document.getElementById('cafe-kiosk');if(!panel){panel=document.createElement('section');panel.id='cafe-kiosk';panel.className='sheet';document.getElementById('app').append(panel);a.register(panel);}
  panel.hidden=false;let previewFinish=null,confirmFinish=null,previewTier=null,confirmShop=false;let workshop=false,recipeResult=null,lessonStep=0;let tasting='',previewEquipment=null,displayState=s;let view='outside',tab=null,frame=0,last=0,timer;const actors=a.actors();stopActive=()=>{cancelAnimationFrame(frame);clearInterval(timer);};
  const money=n=>Math.round(n*10)/10;
  let guideOn=!s.guideDone&&(!s.lessonComplete||s.guideStarted),guideNamed=!!s.recipeNames?.coffee;
  if(guideOn){s.guideStarted=true;a.save();}
  if(guideOn&&s.unlocked){tab='menu';view='inside';}
  function finishGuide(){s.guideDone=true;guideOn=false;a.save();render();}
  function drawGuide(){
   panel.classList.toggle('cc-guiding',guideOn);
   const replay=document.createElement('button');replay.className='btn cc-guide-replay';replay.textContent='Help';replay.setAttribute('aria-label','Help me play: Café guide');replay.onclick=()=>{guideOn=true;s.guideStarted=true;s.guideDone=false;a.save();guideNamed=!!s.lessonComplete;tab='menu';view='inside';workshop=false;recipeResult=null;render();};panel.querySelector('.cc-head').append(replay);
   if(!guideOn)return;
   let title,text,target,step;
   if(!s.unlocked){step=1;title='Let’s make a café!';text='You need 120 Shells. Tap Set up your café when you have enough.';target='[data-start]';}
   else if(!s.lessonComplete){step=1;title='Make a cup';text=workshop?['Tap Add one coffee bean. This cup is free!','Tap Brew my first cup.','Tap Taste my coffee.'][lessonStep]:'Tap Make your first coffee. We will help you.';target=workshop?'[data-lesson]':'[data-create]';}
   else if(recipeResult||!guideNamed){step=2;title='Give it a name';text='Type a fun name. Then tap Save recipe. You can keep the name we picked, too.';target='[data-save-name]';}
   else if(!s.menu.length){step=3;title='Put it on the menu';text='Tap Add to menu beside your drink. This lets cats choose it.';target='[data-recipe]';}
   else if(!s.open){step=4;title='Welcome the cats!';text='Tap Closed at the top to open your café. Cats will make and serve the food for you.';target='[data-pause]';}
   else{step=5;title='You’re open!';text='Cats order on their own. Each order uses ingredients. Tap Grow ingredients to visit the Garden and plant more.';target='[data-garden]';}
   panel.dataset.guideStep=step;
   const card=document.createElement('section');card.className='cc-guide';card.setAttribute('aria-label','Café guide');
   const count=document.createElement('small');count.textContent='LET’S PLAY · '+step+' OF 5';const heading=document.createElement('h3');heading.textContent=title;const copy=document.createElement('p');copy.textContent=text;
   const skip=document.createElement('button');skip.className='btn';skip.textContent=step===5?'Got it':'Skip guide';skip.onclick=finishGuide;card.append(count,heading,copy,skip);
   const host=panel.querySelector('.cc-content:not([hidden])')||panel.querySelector('.cc-intro');if(host)host.prepend(card);
   const action=panel.querySelector(target);if(action){action.classList.add('cc-guide-target');action.setAttribute('aria-describedby','cc-guide-copy');copy.id='cc-guide-copy';}
   else if(s.unlocked){const go=document.createElement('button');go.className='btn primary';go.textContent='Show me';go.onclick=()=>{tab='menu';workshop=step===2;recipeResult=step===2?'coffee':null;render();};card.append(go);if(!host)panel.querySelector('.cc-tabs').after(card);}
  }

  function commit(fn){E.settle(g,Date.now());fn();a.save();a.hud();render();}
  function render(){
   panel.classList.toggle('cc-managing',!!tab);
   cancelAnimationFrame(frame);clearInterval(timer);displayState=previewEquipment?{...s,[previewEquipment]:previewEquipment==='speed'?Math.min(2,s.speed+1):1}:s;
   panel.innerHTML=`<header class="cc-head"><div><h2>Catmint Café</h2></div><button class="btn" data-close aria-label="Return to Cove">Cove</button></header><div class="cc-wallet">${Math.floor(g.shells)} Shells <span>• ${s.served} drinks enjoyed</span></div><div class="cc-switch" aria-label="Café view"><button aria-pressed="${view==='outside'}" data-view="outside">Outside</button><button aria-pressed="${view==='inside'}" data-view="inside">Inside</button></div><canvas aria-label="${view==='inside'?'Behind the counter, customers ordering at the window':'Seaside café kiosk'}" width="720" height="380"></canvas><p class="cc-status" role="status"></p>`;
   panel.querySelector('[data-close]').onclick=()=>{a.close();cancelAnimationFrame(frame);clearInterval(timer);};
   if(s.unlocked){const toggle=document.createElement('button');toggle.className='cc-service';toggle.dataset.pause='';toggle.setAttribute('role','switch');toggle.setAttribute('aria-checked',String(s.open));toggle.setAttribute('aria-label','Open café');toggle.disabled=!s.menu.length||(!s.open&&!E.available(s,g.homestead.stock).length);toggle.title=!s.menu.length?'Add a recipe to your menu first':!s.open&&!E.available(s,g.homestead.stock).length?'Out of ingredients — restock in Pantry':'Open or close your café';toggle.innerHTML='<span>'+ (s.open?'Now Open':s.closedReason==='ingredients'?'Closed · restock':'Closed')+'</span><span class="cc-toggle" aria-hidden="true"></span>';toggle.onclick=()=>commit(()=>{E.setOpen(g,!s.open,Date.now());});panel.querySelector('.cc-head>div').append(toggle);}
   panel.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{view=b.dataset.view;render();});
   if(!s.unlocked){panel.insertAdjacentHTML('beforeend',`<div class="cc-intro"><h3>A little coffee. A lot of company.</h3><p>Your cats handle every order. Grow ingredients, choose the menu, and watch your seaside café come to life.</p><p>Includes 6 coffee beans, 6 catmint and 2 honey. Stock never spoils.</p><button class="btn primary" data-start ${g.shells<120?'disabled':''}>Set up your café · 120 Shells</button><small>Experiment with a drink, add it to your menu, then open for guests.</small></div>`);panel.querySelector('[data-start]').onclick=()=>commit(()=>{E.unlock(g,Date.now());if(guideOn){tab='menu';view='inside';}});}
   else{
    panel.insertAdjacentHTML('beforeend',`<nav class="cc-tabs" aria-label="Café management">${['menu','pantry','report','upgrades'].map(k=>`<button aria-pressed="${tab===k}" data-tab="${k}">${k[0].toUpperCase()+k.slice(1)}</button>`).join('')}</nav><div class="cc-content" ${tab?'':'hidden'}></div>`);
    panel.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{tab=tab===b.dataset.tab?null:b.dataset.tab;render();});const content=panel.querySelector('.cc-content');
    if(tab==='menu'){
     const escape=value=>String(value).replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
     const garden=()=>{if(guideOn&&s.open){s.guideDone=true;a.save();}stopActive();a.garden();};
     if(!workshop){
      content.innerHTML=`<p>When the café is open, recipes on sale are served automatically while ingredients last.</p><button class="btn primary" data-create>${s.lessonComplete?'Create a drink or treat':'Make your first coffee · free lesson'}</button>${E.recipes.filter(r=>s.discovered.includes(r.id)).map(r=>{const level=s.recipeLevels?.[r.id]||0,sales=s.sales[r.id]||0;return `<article class="cc-card"><span class="cc-cup">${cup(r.id)}</span><div><h3>${escape(E.displayName(s,r))}</h3><small>${r.name} · ${E.price(s,r)} Shells</small><small>${Object.entries(r.inputs).map(([k,n])=>n+' '+E.ingredients[k].name.toLowerCase()).join(' + ')}</small><strong class="cc-recipe-state">${s.menu.includes(r.id)?(!s.open?'On menu · café closed':Object.entries(r.inputs).some(([k,n])=>(g.homestead.stock[k]||0)<n)?'On menu · needs ingredients':'On menu · serving automatically'):'Saved recipe · not on menu'}</strong><small>${sales} enjoyed · Recipe level ${level+1}/3</small><details class="cc-recipe-details"><summary>Recipe details & improvements</summary><button class="btn" data-name="${r.id}">Rename</button><button class="btn" data-improve="${r.id}" ${level>=2||sales<(level+1)*10||g.shells<(level+1)*50?'disabled':''}>${level>=2?'Mastered':sales<(level+1)*10?'Serve '+((level+1)*10-sales)+' more to improve':'Improve · '+((level+1)*50)+' Shells · +2 per sale'}</button></details></div><button class="btn" data-recipe="${r.id}" aria-pressed="${s.menu.includes(r.id)}">${s.menu.includes(r.id)?'Remove from menu':'Add to menu'}</button></article>`;}).join('')}<button class="btn" data-garden>Grow ingredients in Cove Garden</button><small>No ingredients? Guests wait patiently. Harvests fill your shared pantry automatically.</small>`;
      content.querySelector('[data-create]').onclick=()=>{workshop=true;recipeResult=null;lessonStep=0;view='inside';render();};
      content.querySelectorAll('[data-recipe]').forEach(b=>b.onclick=()=>commit(()=>{const id=b.dataset.recipe;s.menu=s.menu.includes(id)?s.menu.filter(k=>k!==id):[...s.menu,id];if(!s.menu.length)s.open=false;}));
      content.querySelectorAll('[data-improve]').forEach(b=>b.onclick=()=>commit(()=>E.improve(g,b.dataset.improve)));
      content.querySelectorAll('[data-name]').forEach(b=>b.onclick=()=>{recipeResult=b.dataset.name;workshop=true;render();});
      content.querySelector('[data-garden]').onclick=garden;
     }else{
      content.innerHTML='<button class="btn" data-back-menu>Back to my menu</button><section class="cc-lab"></section>';
      content.querySelector('[data-back-menu]').onclick=()=>{workshop=false;recipeResult=null;render();};
      const lab=content.querySelector('.cc-lab');
      if(recipeResult){
       const recipe=E.recipes.find(r=>r.id===recipeResult);
       lab.innerHTML=`<span class="cc-cup">${cup(recipe.id)}</span><h3>Make it yours</h3><p>${escape(recipe.name)} · ${E.price(s,recipe)} Shells per sale</p><label>Your drink or treat name<input maxlength="24" data-recipe-name aria-label="Recipe name"></label><small>Up to 24 characters. You can rename it later.</small><button class="btn primary" data-save-name>${s.menu.includes(recipe.id)?'Save name · keep serving':'Save recipe · not serving yet'}</button><p role="status"></p>`;
       lab.querySelector('input').value=E.displayName(s,recipe);
       lab.querySelector('[data-save-name]').onclick=()=>{const name=lab.querySelector('input').value;if(!name.trim()){lab.querySelector('[role="status"]').textContent='Give your creation a name first.';return;}commit(()=>{E.nameRecipe(g,recipe.id,name);guideNamed=true;workshop=false;recipeResult=null;});};
      }else if(!s.lessonComplete){
       lab.innerHTML=`<h3>Your first coffee</h3><span class="cc-cup">${cup('coffee')}</span><p>${['Start with one coffee bean. This practice cup is on us.','The bean is ready. Brew it slowly.','A lovely first cup. Taste it and make it yours.'][lessonStep]}</p><button class="btn primary" data-lesson>${['Add one coffee bean','Brew my first cup','Taste my coffee'][lessonStep]}</button><small>Free guided lesson · no pantry ingredients used.</small>`;
       lab.querySelector('[data-lesson]').onclick=()=>{if(lessonStep<2){lessonStep++;render();}else commit(()=>{const result=E.lesson(g);recipeResult=result.id||null;tasting=result.message||result.error;});};
      }else{
       lab.innerHTML='<h3>Try a new recipe</h3><p>Choose a recipe card for guidance, or change the amounts to experiment.</p><div class="cc-recipe-guides">'+E.recipes.map(r=>'<button class="btn" data-guide="'+r.id+'">'+escape(r.name)+'</button>').join('')+'</div>'+Object.entries(E.ingredients).map(([k,v])=>'<label>'+v.name+' · '+(g.homestead.stock[k]||0)+' in pantry<select data-mix="'+k+'"><option>0</option><option>1</option><option>2</option><option>3</option></select></label>').join('')+'<small>Each attempt uses the selected ingredients, including unsuccessful batches.</small><button class="btn primary" data-brew>Make & taste</button><p role="status"></p><button class="btn" data-garden>Grow ingredients in Cove Garden</button>';
       lab.querySelector('[role="status"]').textContent=tasting;
       const availability=()=>{const missing=[];let total=0;lab.querySelectorAll('[data-mix]').forEach(el=>{const amount=Number(el.value),have=g.homestead.stock[el.dataset.mix]||0;total+=amount;if(amount>have)missing.push(E.ingredients[el.dataset.mix].name+': need '+amount+', have '+have);});lab.querySelector('[data-brew]').disabled=!total||missing.length>0;lab.querySelector('[role="status"]').textContent=missing.length?'Not enough ingredients — '+missing.join('; ')+'. Harvest in the Garden or restock in Pantry.':!total?(tasting||'Choose a recipe or ingredients first.'):'Ingredients ready. You can make this batch.';};
       lab.querySelectorAll('[data-mix]').forEach(el=>el.onchange=availability);
       lab.querySelectorAll('[data-guide]').forEach(b=>b.onclick=()=>{const r=E.recipes.find(r=>r.id===b.dataset.guide);lab.querySelectorAll('[data-mix]').forEach(el=>el.value=String(r.inputs[el.dataset.mix]||0));availability();});availability();
       lab.querySelector('[data-brew]').onclick=()=>{const mix={};lab.querySelectorAll('[data-mix]').forEach(el=>mix[el.dataset.mix]=Number(el.value));commit(()=>{const result=E.experiment(g,mix);tasting=result.error||result.message;recipeResult=result.id||null;});};
       lab.querySelector('[data-garden]').onclick=garden;
      }
     }
    }else if(tab==='pantry'){
     content.innerHTML=`<p>Grow for better margins, or import a little convenience. Imports always require your tap.</p>${Object.entries(E.ingredients).map(([k,v])=>`<article class="cc-card"><div><h3>${v.name} <span class="cc-count">${g.homestead.stock[k]||0}</span></h3><small>Import ${v.import} Shells each · grow ${v.yield} for ${v.cost}</small></div><button class="btn" data-import="${k}" ${g.shells<v.import*5?'disabled':''}>Buy 5 · ${v.import*5}</button></article>`).join('')}<button class="btn primary" data-garden>Visit Cove Garden</button>`;content.querySelectorAll('[data-import]').forEach(b=>b.onclick=()=>commit(()=>{const k=b.dataset.import,cost=E.ingredients[k].import*5;if(g.shells>=cost){g.shells-=cost;E.acquire(g,k,5,cost);}}));content.querySelector('[data-garden]').onclick=()=>{cancelAnimationFrame(frame);clearInterval(timer);a.garden();};
     const plan=E.pantryPlan(g),overview=document.createElement('section');overview.className='cc-pantry-plan';const heading=document.createElement('h3');heading.textContent='Keep your menu serving';overview.append(heading);const goal=document.createElement('p');goal.textContent=plan.selected.length?'Stock goal: five more orders of every recipe on sale. Ingredients are shared between recipes.':'Start serving a recipe in My Menu to get planting recommendations.';overview.append(goal);overview.append(content.querySelector('[data-garden]'));
     for(const recipe of plan.selected){const p=document.createElement('p');p.textContent=recipe.name+': '+'up to '+recipe.orders+' order'+(recipe.orders===1?'':'s')+' from current stock.';overview.append(p);}
     for(const row of plan.rows.filter(r=>r.target)){const card=document.createElement('article');card.className='cc-card';const body=document.createElement('div');const name=document.createElement('h3');name.textContent=row.name+' · '+row.have+' in pantry';const detail=document.createElement('p');detail.textContent='Goal '+row.target+' · '+row.growing+' in Garden'+(row.ready?' ('+row.ready+' ready to harvest)':'');const action=document.createElement('small');action.textContent=row.ready&&row.short?'Harvest ready patches first.':row.plant?'Plant '+row.patches+' patch'+(row.patches===1?'':'es')+' · '+row.cost*row.patches+' Shells · '+Math.ceil(row.seconds/60)+' min per harvest.':row.short?'Already growing enough. Harvest when ready.':'Enough stocked for this goal.';const use=document.createElement('small');use.textContent='For '+row.usedBy.join(', ');body.append(name,detail,action,use);card.append(body);overview.append(card);}content.prepend(overview);
    }else if(tab==='report'){
     const best=E.recipes.slice().sort((a,b)=>(s.sales[b.id]||0)-(s.sales[a.id]||0))[0];const low=Object.keys(E.ingredients).sort((a,b)=>(g.homestead.stock[a]||0)-(g.homestead.stock[b]||0))[0];
     content.innerHTML=`<p class="cc-report-line">${s.served?'“The cups are empty. The hearts are full.”':'“Midknight has inspected the counter. Twice.”'}</p><div class="cc-stats">${[['Served',s.served],['Sales',money(s.revenue)],['Ingredient cost',money(s.cost+(s.experimentCost||0))],['Net profit',money(s.revenue-s.cost-(s.experimentCost||0))]].map(([k,v])=>`<div><small>${k}</small><strong>${v}</strong></div>`).join('')}</div><p>${s.served?'Best seller: '+best.name+' · '+s.sales[best.id]+' cups':'Your first sale will appear here.'}</p><p>Garden tip: ${E.ingredients[low].name.toLowerCase()} is your lowest stock.</p><button class="btn primary" data-garden>Visit Cove Garden</button><small class="cc-note">Lifetime figures. Costs follow ingredients used, including growing costs. Starter ingredients are complimentary. Stock-limited offline service runs for up to 12 hours; unused ingredients stay safe.</small>`;content.querySelector('[data-garden]').onclick=()=>{cancelAnimationFrame(frame);clearInterval(timer);a.garden();};
     const feedback=document.createElement('section');feedback.className='cc-feedback';const report=s.customerReport||{total:0,happy:0,delighted:0};
     feedback.innerHTML='<h3>Customer happiness</h3><p>'+report.happy+' happy of '+report.total+' rated visits · '+report.delighted+' delighted</p><small>In-game reactions since this update. Improving recipes helps earn warmer feedback.</small>';
     for(const visit of s.feedbackLog||[]){const recipe=E.recipes.find(r=>r.id===visit.id);if(!recipe)continue;const card=document.createElement('article');card.className='cc-card';const body=document.createElement('div'),title=document.createElement('h3'),quote=document.createElement('p');title.textContent=E.displayName(s,recipe)+' · '+(visit.rating===5?'Delighted':visit.rating>=4?'Happy':'Room to improve');quote.textContent='“'+visit.text+'”';body.append(title,quote);card.append(body);feedback.append(card);}content.prepend(feedback);
    }else{
     content.innerHTML=`<p>Equipment you can see inside your café.</p><article class="cc-card"><div><h3>Coffee machine</h3><p>One guest every ${E.interval(s)/60000} minutes.</p><small>Level ${s.speed+1}/3 · no rushed cats</small></div><button class="btn" data-speed ${s.speed>=2||g.shells<(s.speed+1)*300?'disabled':''}>${s.speed>=2?'Complete':'Upgrade · '+(s.speed+1)*300}</button></article><article class="cc-card"><div><h3>A table by the sea</h3><p>A cozy outdoor table and cushion.</p><small>Visual upgrade · no extra income multiplier</small></div><button class="btn" data-seat ${s.seats||g.shells<150?'disabled':''}>${s.seats?'Placed':'Add · 150'}</button></article><article class="cc-card"><div><h3>Copper cookware</h3><p>A copper kettle and lidded pot for your counter.</p><small>Visual upgrade · no income multiplier</small></div><button class="btn" data-cookware ${s.cookware||g.shells<180?'disabled':''}>${s.cookware?'Owned':'Add · 180'}</button></article>`;content.querySelector('[data-cookware]').onclick=()=>commit(()=>{if(!s.cookware&&g.shells>=180){g.shells-=180;s.cookware=true;view='inside';}});content.querySelector('[data-speed]').onclick=()=>commit(()=>{const n=(s.speed+1)*300;if(s.speed<2&&g.shells>=n){g.shells-=n;s.speed++;view='inside';}});content.querySelector('[data-seat]').onclick=()=>commit(()=>{if(!s.seats&&g.shells>=150){g.shells-=150;s.seats=1;}});
    }
   }
   if(tab==='upgrades'&&s.unlocked&&view==='outside'){
    const tier=s.shopTier||0,next=E.shops[tier+1],box=document.createElement('div');box.className='cc-shop-stages';
    box.innerHTML=`<h3>Your café, growing with you</h3><p>Three shop stages. Keep every machine, ingredient and sale when you expand. Buildings change the shop; brewing speed stays with your machine.</p>${E.shops.map((shop,i)=>`<article class="cc-card"><div><h3>${i+1}. ${shop.name}</h3><small>${shop.description}</small><small>${i<=tier?(i===tier?'Current shop':'Completed'):shop.cost.toLocaleString()+' Shells'+(i>tier+1?' · previous stage required':'')}</small></div><button class="btn" data-preview="${i}">Preview</button></article>`).join('')}<button class="btn" data-current>Show my shop</button>${next?`<p>${Math.max(0,next.cost-Math.floor(g.shells)).toLocaleString()} Shells to save for ${next.name}. Each stage has its own price.</p><button class="btn primary" data-expand ${g.shells<next.cost?'disabled':''}>${confirmShop?'Confirm · spend '+next.cost.toLocaleString()+' Shells':'Expand · '+next.cost.toLocaleString()+' Shells'}</button>${confirmShop?'<button class="btn" data-cancel-expand>Cancel</button>':''}`:'<p>Your Seaside Café is fully expanded.</p>'}`;
    panel.querySelector('.cc-content').prepend(box);
    box.querySelectorAll('[data-preview]').forEach(b=>b.onclick=()=>{tab=null;previewTier=Number(b.dataset.preview);confirmShop=false;render();panel.scrollTop=0;});
    box.querySelector('[data-current]').onclick=()=>{previewTier=null;previewFinish=null;confirmFinish=null;confirmShop=false;render();panel.scrollTop=0;};
    if(next)box.querySelector('[data-expand]').onclick=()=>{if(!confirmShop){confirmShop=true;render();return;}commit(()=>{E.upgradeShop(g,Date.now());previewTier=null;confirmShop=false;});};
    box.querySelector('[data-cancel-expand]')?.addEventListener('click',()=>{confirmShop=false;render();});
   }
   if(tab==='upgrades'&&s.unlocked&&view==='outside'){
    const finishes=document.createElement('section');finishes.className='cc-finishes';
    finishes.innerHTML='<h3>Make it your color</h3><p>Preview any finish free. Unlock once, then switch whenever you like. Colors are purely decorative.</p><div class="cc-finish-grid">'+Object.entries(E.finishes).map(([key,f])=>{const owned=key==='sage'||(s.finishesOwned||[]).includes(key),current=(s.finish||'sage')===key;return `<article><span class="cc-swatch" style="background:${f.body};border-bottom-color:${f.dark}"></span><h3>${f.name}</h3><small>${owned?'Owned':f.cost.toLocaleString()+' Shells'}</small><button class="btn" data-finish-preview="${key}">Preview</button><button class="btn primary" data-finish-buy="${key}" ${current||(!owned&&g.shells<f.cost)?'disabled':''}>${current?'In use':owned?'Use finish':confirmFinish===key?'Confirm purchase':'Unlock'}</button></article>`;}).join('')+'</div>';
    panel.querySelector('.cc-shop-stages').after(finishes);
    finishes.querySelectorAll('[data-finish-preview]').forEach(b=>b.onclick=()=>{tab=null;previewFinish=b.dataset.finishPreview;confirmFinish=null;view='outside';render();panel.scrollTop=0;});
    finishes.querySelectorAll('[data-finish-buy]').forEach(b=>b.onclick=()=>{const key=b.dataset.finishBuy,owned=key==='sage'||(s.finishesOwned||[]).includes(key);if(!owned&&confirmFinish!==key){confirmFinish=key;render();return;}commit(()=>{E.buyFinish(g,key);previewFinish=null;confirmFinish=null;});});
   }
   if(previewFinish){const note=document.createElement('p');note.className='cc-note';note.textContent='Color preview: '+E.finishes[previewFinish].name+' · no Shells spent.';panel.querySelector('canvas').before(note);}
   if(previewTier!==null){const note=document.createElement('p');note.className='cc-note';note.textContent='Preview: '+E.shops[previewTier].name+' · your shop and Shells have not changed.';panel.querySelector('canvas').before(note);}
   if(tab==='upgrades'){
    const content=panel.querySelector('.cc-content');
    if(view==='outside'){const intro=content.querySelector(':scope > p');if(intro)intro.textContent='Your storefront and outdoor seating.';content.querySelectorAll('[data-speed],[data-cookware]').forEach(b=>b.closest('article').remove());}
    else{content.querySelector('[data-seat]')?.closest('article').remove();}
    for(const [key,selector]of [['speed','[data-speed]'],['cookware','[data-cookware]'],['seats','[data-seat]']]){const buy=content.querySelector(selector);if(!buy)continue;const preview=document.createElement('button');preview.className='btn';preview.textContent='Preview';preview.onclick=()=>{previewEquipment=key;tab=null;render();};buy.before(preview);}
   }
   if(previewEquipment){const note=document.createElement('button');note.className='btn';note.textContent='Previewing upgrade · Back';note.onclick=()=>{previewEquipment=null;tab='upgrades';render();};panel.querySelector('canvas').before(note);}
   const drawer=panel.querySelector('.cc-content');
   if(drawer&&tab){drawer.insertAdjacentHTML('afterbegin','<div class="cc-drawer-head"><h3>'+tab[0].toUpperCase()+tab.slice(1)+'</h3><button class="btn" data-dismiss>Close</button></div>');drawer.querySelector('[data-dismiss]').onclick=()=>{tab=null;render();};}
   const cv=panel.querySelector('canvas');cv.onclick=e=>{if(view!=='outside'||tab)return;const b=cv.getBoundingClientRect(),fit=b.width/720,x=(e.clientX-b.left)/fit,y=(e.clientY-b.top)/fit-Math.max(0,720*b.height/Math.max(1,b.width)-380)*.45;if(x>190&&x<530&&y>100&&y<235){view='inside';render();}else if(x>25&&x<120&&y>270&&y<350){panel.querySelector('.cc-sale')?.remove();const hello=document.createElement('div');hello.className='cc-sale';hello.setAttribute('role','status');hello.textContent=['This seat has excellent purr acoustics.','Stay a little. The sea isn’t going anywhere.','A quiet bench. Very important cat business.'][Math.floor(Date.now()/1000)%3];panel.append(hello);setTimeout(()=>hello.remove(),4500);}};
   panel.onkeydown=e=>{if(e.key==='Escape'){if(tab){tab=null;render();}else panel.querySelector('[data-close]').click();}};
   panel.querySelector('.cc-switch').insertAdjacentHTML('afterend','<p class="cc-visit-hint">'+(view==='outside'?'Tap the serving window to step inside.':'A warm cup and a little company.')+'</p>');
   drawGuide();
   const renderedServed=s.served,renderedOpen=s.open,renderedPending=s.pending?.at;status();frame=requestAnimationFrame(paint);timer=setInterval(()=>{if(panel.hidden||!panel.isConnected){clearInterval(timer);cancelAnimationFrame(frame);return;}const before=s.served;E.settle(g,Date.now());if(s.served!==renderedServed){a.save();a.hud();render();const notice=document.createElement('div');notice.className='cc-sale';notice.setAttribute('role','status');const sold=E.recipes.find(r=>r.id===s.lastCompleted?.id);notice.textContent=sold?E.displayName(s,sold)+' · +'+(s.lastCompleted.price||E.price(s,sold))+' Shells — '+(s.lastCompleted.response?.text||'A happy little moment.'):'An order enjoyed · Shells added';panel.append(notice);setTimeout(()=>notice.remove(),4000);}else if(s.open!==renderedOpen||s.pending?.at!==renderedPending){a.save();render();}else status();},1000);
  }
  function status(){const el=panel.querySelector('.cc-status');if(!el)return;const n=Math.max(0,Math.ceil((s.cursor+E.interval(s)-Date.now())/1000));el.textContent=!s.unlocked?'A tiny place for your next big idea.':s.pending?'Brewing '+E.displayName(s,E.recipes.find(r=>r.id===s.pending.id))+' · ready in '+Math.max(0,Math.ceil((s.pending.at-Date.now())/1000))+'s':!s.menu.length?'Create a drink and add it to your menu before opening.':!s.open?(s.closedReason==='ingredients'?'Closed · out of ingredients. Restock in Pantry or grow more in the Garden.':'Ready when you are · tap Closed above to open.'):!E.available(s,g.homestead.stock).length?'Taking a nap · stock an ingredient or add a drink to the menu.':`Open · next guest in ${Math.floor(n/60)}:${String(n%60).padStart(2,'0')}`;}
  function cup(id){if(id==='bites')return '<svg viewBox="0 0 60 64" aria-label="Garden bites"><ellipse cx="30" cy="47" rx="28" ry="10" fill="#ddd0ad"/><circle cx="20" cy="35" r="12" fill="#c78e55"/><circle cx="39" cy="38" r="12" fill="#d6a366"/><path d="m14 31 10 7m10-5 8 9" stroke="#a77149" stroke-width="3"/></svg>';return `<svg viewBox="0 0 60 64" aria-hidden="true"><path d="M42 24h8q12 15-8 19" fill="none" stroke="#ae8761" stroke-width="5"/><path d="M10 20h34v26q-17 15-34 0Z" fill="${id==='tea'?'#8fa783':id==='midknight'?'#d0ad6b':'#e5cfa8'}"/><ellipse cx="27" cy="21" rx="17" ry="5" fill="#74523d"/><path d="M22 13q-7-6 0-11m12 11q-7-6 0-11" fill="none" stroke="#adbaa0" stroke-width="2"/></svg>`;}
  function paint(t){
   if(panel.hidden||!panel.isConnected)return;frame=requestAnimationFrame(paint);if(document.hidden||t-last<33)return;last=t;
   const canvas=panel.querySelector('canvas'),bounds=canvas.getBoundingClientRect(),height=Math.max(380,Math.round(720*bounds.height/Math.max(1,bounds.width)));const density=Math.min(window.devicePixelRatio||1,2),width=Math.max(720,Math.round(bounds.width*density)),pixelHeight=Math.round(height*width/720);if(canvas.width!==width||canvas.height!==pixelHeight){canvas.width=width;canvas.height=pixelHeight;}const ctx=canvas.getContext('2d');ctx.setTransform(width/720,0,0,width/720,0,0);
   CoveCafeScene(ctx,{height,inside:view==='inside',s:displayState,stock:g.homestead.stock,E,a,actors,t,previewTier,previewFinish});
  }
  render();
 }};
})(globalThis);
