(function(root){
 'use strict';
 let stopActive=()=>{};
 root.CoveCafeView={open(a){
  stopActive();
  const E=root.CoveCafeEngine,g=a.game(),s=E.init(g,Date.now());a.close();
  let panel=document.getElementById('cafe-kiosk');if(!panel){panel=document.createElement('section');panel.id='cafe-kiosk';panel.className='sheet';document.getElementById('app').append(panel);a.register(panel);}
  panel.hidden=false;let previewTier=null,confirmShop=false;let view='outside',tab='menu',frame=0,last=0,timer;const actors=a.actors();stopActive=()=>{cancelAnimationFrame(frame);clearInterval(timer);};
  const money=n=>Math.round(n*10)/10;
  function commit(fn){E.settle(g,Date.now());fn();a.save();a.hud();render();}
  function render(){
   cancelAnimationFrame(frame);clearInterval(timer);
   panel.innerHTML=`<header class="cc-head"><div><small>YOUR SEASIDE COFFEE STOP</small><h2>Catmint Café</h2></div><button class="btn" data-close>Close</button></header><div class="cc-wallet">${Math.floor(g.shells)} Shells <span>• ${s.served} drinks enjoyed</span></div><div class="cc-switch" aria-label="Café view"><button aria-pressed="${view==='outside'}" data-view="outside">Outside</button><button aria-pressed="${view==='inside'}" data-view="inside">Inside</button></div><canvas aria-label="${view==='inside'?'Behind the counter, customers ordering at the window':'Seaside café kiosk'}" width="720" height="380"></canvas><p class="cc-status" role="status"></p>`;
   panel.querySelector('[data-close]').onclick=()=>{a.close();cancelAnimationFrame(frame);clearInterval(timer);};
   panel.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{view=b.dataset.view;render();});
   if(!s.unlocked){panel.insertAdjacentHTML('beforeend',`<div class="cc-intro"><h3>A little coffee. A lot of company.</h3><p>Your cats handle every order. Grow ingredients, choose the menu, and watch your seaside café come to life.</p><p>Includes 6 coffee beans, 6 catmint and 2 honey. Stock never spoils.</p><button class="btn primary" data-start ${g.shells<120?'disabled':''}>Open your café · 120 Shells</button><small>Your first guest arrives in 30 seconds. No tapping to serve.</small></div>`);panel.querySelector('[data-start]').onclick=()=>commit(()=>E.unlock(g,Date.now()));}
   else{
    panel.insertAdjacentHTML('beforeend',`<nav class="cc-tabs" aria-label="Café management">${['menu','pantry','report','upgrades'].map(k=>`<button aria-pressed="${tab===k}" data-tab="${k}">${k[0].toUpperCase()+k.slice(1)}</button>`).join('')}</nav><div class="cc-content"></div>`);
    panel.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;render();});const content=panel.querySelector('.cc-content');
    if(tab==='menu'){
     content.innerHTML=`<p>Customers order automatically; your cats do the brewing. Sales go straight to your Shells.</p>${E.recipes.map(r=>{const missing=Object.entries(r.inputs).filter(([k,n])=>(g.homestead.stock[k]||0)<n).map(([k])=>E.ingredients[k].name);return `<article class="cc-card"><span class="cc-cup">${cup(r.id)}</span><div><h3>${r.name}</h3><p>${r.note}</p><small>${Object.entries(r.inputs).map(([k,n])=>n+' '+E.ingredients[k].name.toLowerCase()).join(' + ')} · ${r.price} Shells</small><small>${missing.length?'Sold out · Needs '+missing.join(', '):'Ready to brew'}</small></div><button class="btn" data-recipe="${r.id}" aria-pressed="${s.menu.includes(r.id)}">${s.menu.includes(r.id)?'On menu':'Add'}</button></article>`;}).join('')}<button class="btn" data-pause>${s.open?'Pause service':'Open café'}</button><small class="cc-note">Paused cafés finish accepted orders. Guests never mind a stockout.</small>`;
     content.querySelectorAll('[data-recipe]').forEach(b=>b.onclick=()=>commit(()=>{const id=b.dataset.recipe;s.menu=s.menu.includes(id)?s.menu.filter(k=>k!==id):[...s.menu,id];}));content.querySelector('[data-pause]').onclick=()=>commit(()=>{s.open=!s.open;s.cursor=Date.now();});
    }else if(tab==='pantry'){
     content.innerHTML=`<p>Grow for better margins, or import a little convenience. Imports always require your tap.</p>${Object.entries(E.ingredients).map(([k,v])=>`<article class="cc-card"><div><h3>${v.name} <span class="cc-count">${g.homestead.stock[k]||0}</span></h3><small>Import ${v.import} Shells each · grow ${v.yield} for ${v.cost}</small></div><button class="btn" data-import="${k}" ${g.shells<v.import*5?'disabled':''}>Buy 5 · ${v.import*5}</button></article>`).join('')}<button class="btn primary" data-garden>Visit Cove Garden</button>`;content.querySelectorAll('[data-import]').forEach(b=>b.onclick=()=>commit(()=>{const k=b.dataset.import,cost=E.ingredients[k].import*5;if(g.shells>=cost){g.shells-=cost;E.acquire(g,k,5,cost);}}));content.querySelector('[data-garden]').onclick=()=>{cancelAnimationFrame(frame);clearInterval(timer);a.garden();};
    }else if(tab==='report'){
     const best=E.recipes.slice().sort((a,b)=>(s.sales[b.id]||0)-(s.sales[a.id]||0))[0];const low=Object.keys(E.ingredients).sort((a,b)=>(g.homestead.stock[a]||0)-(g.homestead.stock[b]||0))[0];
     content.innerHTML=`<p class="cc-report-line">${s.served?'“The cups are empty. The hearts are full.”':'“Midknight has inspected the counter. Twice.”'}</p><div class="cc-stats">${[['Served',s.served],['Sales',money(s.revenue)],['Ingredient cost',money(s.cost)],['Net profit',money(s.revenue-s.cost)]].map(([k,v])=>`<div><small>${k}</small><strong>${v}</strong></div>`).join('')}</div><p>${s.served?'Best seller: '+best.name+' · '+s.sales[best.id]+' cups':'Your first sale will appear here.'}</p><p>Garden tip: ${E.ingredients[low].name.toLowerCase()} is your lowest stock.</p><button class="btn primary" data-garden>Visit Cove Garden</button><small class="cc-note">Lifetime figures. Costs follow ingredients used, including growing costs. Starter ingredients are complimentary. Stock-limited offline service runs for up to 12 hours; unused ingredients stay safe.</small>`;content.querySelector('[data-garden]').onclick=()=>{cancelAnimationFrame(frame);clearInterval(timer);a.garden();};
    }else{
     content.innerHTML=`<p>Equipment you can see inside your café.</p><article class="cc-card"><div><h3>Coffee machine</h3><p>One guest every ${E.interval(s)/60000} minutes.</p><small>Level ${s.speed+1}/3 · no rushed cats</small></div><button class="btn" data-speed ${s.speed>=2||g.shells<(s.speed+1)*300?'disabled':''}>${s.speed>=2?'Complete':'Upgrade · '+(s.speed+1)*300}</button></article><article class="cc-card"><div><h3>A table by the sea</h3><p>A cozy outdoor table and cushion.</p><small>Visual upgrade · no extra income multiplier</small></div><button class="btn" data-seat ${s.seats||g.shells<150?'disabled':''}>${s.seats?'Placed':'Add · 150'}</button></article><article class="cc-card"><div><h3>Copper cookware</h3><p>A copper kettle and lidded pot for your counter.</p><small>Visual upgrade · no income multiplier</small></div><button class="btn" data-cookware ${s.cookware||g.shells<180?'disabled':''}>${s.cookware?'Owned':'Add · 180'}</button></article>`;content.querySelector('[data-cookware]').onclick=()=>commit(()=>{if(!s.cookware&&g.shells>=180){g.shells-=180;s.cookware=true;view='inside';}});content.querySelector('[data-speed]').onclick=()=>commit(()=>{const n=(s.speed+1)*300;if(s.speed<2&&g.shells>=n){g.shells-=n;s.speed++;view='inside';}});content.querySelector('[data-seat]').onclick=()=>commit(()=>{if(!s.seats&&g.shells>=150){g.shells-=150;s.seats=1;}});
    }
   }
   if(tab==='upgrades'&&s.unlocked){
    const tier=s.shopTier||0,next=E.shops[tier+1],box=document.createElement('div');box.className='cc-shop-stages';
    box.innerHTML=`<h3>Your café, growing with you</h3><p>Three shop stages. Keep every machine, ingredient and sale when you expand. Buildings change the shop; brewing speed stays with your machine.</p>${E.shops.map((shop,i)=>`<article class="cc-card"><div><h3>${i+1}. ${shop.name}</h3><small>${shop.description}</small><small>${i<=tier?(i===tier?'Current shop':'Completed'):shop.cost.toLocaleString()+' Shells'+(i>tier+1?' · previous stage required':'')}</small></div><button class="btn" data-preview="${i}">Preview</button></article>`).join('')}<button class="btn" data-current>Show my shop</button>${next?`<p>${Math.max(0,next.cost-Math.floor(g.shells)).toLocaleString()} Shells to save for ${next.name}. Each stage has its own price.</p><button class="btn primary" data-expand ${g.shells<next.cost?'disabled':''}>${confirmShop?'Confirm · spend '+next.cost.toLocaleString()+' Shells':'Expand · '+next.cost.toLocaleString()+' Shells'}</button>${confirmShop?'<button class="btn" data-cancel-expand>Cancel</button>':''}`:'<p>Your Seaside Café is fully expanded.</p>'}`;
    panel.querySelector('.cc-content').prepend(box);
    box.querySelectorAll('[data-preview]').forEach(b=>b.onclick=()=>{previewTier=Number(b.dataset.preview);confirmShop=false;render();panel.scrollTop=0;});
    box.querySelector('[data-current]').onclick=()=>{previewTier=null;confirmShop=false;render();panel.scrollTop=0;};
    if(next)box.querySelector('[data-expand]').onclick=()=>{if(!confirmShop){confirmShop=true;render();return;}commit(()=>{E.upgradeShop(g,Date.now());previewTier=null;confirmShop=false;});};
    box.querySelector('[data-cancel-expand]')?.addEventListener('click',()=>{confirmShop=false;render();});
   }
   if(previewTier!==null){const note=document.createElement('p');note.className='cc-note';note.textContent='Preview: '+E.shops[previewTier].name+' · your shop and Shells have not changed.';panel.querySelector('canvas').before(note);}
   const renderedServed=s.served;status();frame=requestAnimationFrame(paint);timer=setInterval(()=>{if(panel.hidden||!panel.isConnected){clearInterval(timer);cancelAnimationFrame(frame);return;}const before=s.served;E.settle(g,Date.now());if(s.served!==renderedServed){a.save();a.hud();render();}else status();},1000);
  }
  function status(){const el=panel.querySelector('.cc-status');if(!el)return;const n=Math.max(0,Math.ceil((s.cursor+E.interval(s)-Date.now())/1000));el.textContent=!s.unlocked?'A tiny place for your next big idea.':s.pending?'Brewing '+E.recipes.find(r=>r.id===s.pending.id).name+' · a guest is waiting':!s.open?'Closed for a little rest.':!E.available(s,g.homestead.stock).length?'Taking a nap · stock an ingredient or add a drink to the menu.':`Open · next guest in ${Math.floor(n/60)}:${String(n%60).padStart(2,'0')}`;}
  function cup(id){return `<svg viewBox="0 0 60 64" aria-hidden="true"><path d="M42 24h8q12 15-8 19" fill="none" stroke="#ae8761" stroke-width="5"/><path d="M10 20h34v26q-17 15-34 0Z" fill="${id==='tea'?'#8fa783':id==='midknight'?'#d0ad6b':'#e5cfa8'}"/><ellipse cx="27" cy="21" rx="17" ry="5" fill="#74523d"/><path d="M22 13q-7-6 0-11m12 11q-7-6 0-11" fill="none" stroke="#adbaa0" stroke-width="2"/></svg>`;}
  function paint(t){
   if(panel.hidden||!panel.isConnected)return;frame=requestAnimationFrame(paint);if(document.hidden||t-last<33)return;last=t;
   CoveCafeScene(panel.querySelector('canvas').getContext('2d'),{inside:view==='inside',s,stock:g.homestead.stock,E,a,actors,t,previewTier});
  }
  render();
 }};
})(globalThis);
