/* Little Matches — isolated activity state, persisted in the existing Neo save. */
window.createLittleMatches=function(api){
'use strict';
const chapters=['Familiar Faces','Favourite Things','A Place Together'];
const curve=[3,3,4,3,4,4,3,4,4,4,4,4,5,4,5,5,4,6,5,6,5,6,6,5,6,7,5,7,7,8];
const coatPools=[['ginger','black','white','siamese','calico','rosewater','tuxedo','browntab'],['ginger','white','calico','siamese','tuxedo','russian','cream','rosewater'],['prism','rosewater','van','smoke','lynxpoint','silver','greytab','tuxedo','ginger','white']];
const objKeys=['food','bed','toy','flowers','lantern','birdbath','windmill','bunting'];
const favours={peek:['Little peek','Choose four cards to see briefly.'],friend:['Find a friend','Turn over one card; your cat finds its pair.'],second:['Second look','See your previous two cards again.']};
let roster=[],catalog=null,dlg=null,round=null,first=null,busy=false,picking=false,picks=[],timer=null,epoch=0,revealed=[],speaker=0;
const reduced=()=>matchMedia('(prefers-reduced-motion: reduce)').matches;
const state=()=>{const s=api.state();s.done ||= {};s.tone ||= 'sage';return s};
const persist=()=>{state().round=round;api.save()};
function rng(seed){return()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296}}
function shuffle(a,r){a=a.slice();for(let i=a.length-1;i;i--){const j=Math.floor(r()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function build(n){const r=rng(n*1777+83),ch=Math.floor((n-1)/10),size=curve[n-1];let keys=shuffle(coatPools[ch],r).slice(0,ch===0?size:Math.ceil(size/2)).map(k=>'cat:'+k);if(ch>0)keys.push(...shuffle(objKeys,r).slice(0,size-keys.length).map(k=>'obj:'+k));return shuffle(keys.flatMap(k=>[k,k]),r)}
function el(tag,cls,text){const e=document.createElement(tag);if(cls)e.className=cls;if(text!==undefined)e.textContent=text;return e}
function button(text,fn,primary=false){const b=el('button','lm-btn'+(primary?' lm-primary':''),text);b.type='button';b.onclick=fn;return b}
function img(key,cls){const i=el('img',cls);i.src=catalog[key].image;i.alt='';return i}
function companion(){return roster.find(c=>c.id===round?.cat)||roster[0]||{name:'Your companion',key:'midknight'}}
function say(text){const t=dlg.querySelector('.lm-speech');if(t)t.textContent=text}
function clear(){if(round?.shufflePending)openingShuffle();epoch++;clearTimeout(timer);timer=null;busy=false;picking=false;picks=[];revealed=[];first=null}
function close(){clear();persist();dlg.close()}
function pauseReveal(indices,message){busy=true;revealed=indices;renderBoard();say(message);const e=epoch;timer=setTimeout(()=>{if(e!==epoch)return;revealed=[];busy=false;renderBoard();persist()},2200)}
function start(n,favour,cat){clear();round={level:n,deck:build(n),matched:[],turns:0,used:false,favour,cat,last:[],finished:false};persist();play();openingLook();}
function openingShuffle(){
 let order=shuffle(round.deck.map((_,i)=>i),Math.random);
 if(order.every((old,i)=>round.deck[old]===round.deck[i])){const shift=round.deck.findIndex(k=>k!==round.deck[0]);order=round.deck.map((_,i)=>(i+shift)%round.deck.length);}
 round.deck=order.map(i=>round.deck[i]);round.shufflePending=false;persist();return order;
}
function openingLook(){
 busy=true;round.shufflePending=true;persist();revealed=round.deck.map((_,i)=>i);renderBoard();say('Meet this little gathering. A shuffle comes next.');
 const board=dlg.querySelector('.lm-board');if(!reduced())board.classList.add('lm-deal');
 const skip=button('Start now',()=>{if(e!==epoch)return;if(round.shufflePending)openingShuffle();finish();},true);skip.id='lm-start-now';dlg.querySelector('.lm-main .lm-actions').prepend(skip);
 const e=epoch;
 function finish(){if(e!==epoch)return;clearTimeout(timer);timer=null;board.getAnimations({subtree:true}).forEach(a=>a.cancel());revealed=[];busy=false;board.classList.remove('lm-deal');skip.remove();renderBoard();say('Find their friends. Their places stay fixed now.');persist();}
 function mix(){if(e!==epoch)return;revealed=[];board.classList.remove('lm-deal');renderBoard();const old=[...board.children].map(c=>c.getBoundingClientRect());const order=openingShuffle();renderBoard();say('A little shuffle…');
 if(!reduced()){[...board.children].forEach((card,i)=>{const to=card.getBoundingClientRect(),from=old[order[i]];card.animate([{transform:'translate('+ (from.x-to.x)+'px,'+(from.y-to.y)+'px) scale(.88)'},{transform:'translate(0,0) scale(1)'}],{duration:950,easing:'ease-in-out'});});}
 timer=setTimeout(finish,reduced()?350:1050);
 }
 timer=setTimeout(mix,3000);
}
function home(){clear();dlg.replaceChildren();const top=el('div','lm-top');top.append(el('div','lm-kicker','WEB PLAYTEST · 30 LEVELS'),button('Back to Cove',close));dlg.append(top,el('h2','','Little Matches'),el('p','lm-intro','Familiar faces. Favourite things. A little place together.'));
 const options=el('div','lm-setup');const label=el('label','','Keep me company');const select=el('select');select.id='lm-cat';for(const c of roster){const o=el('option','',c.name);o.value=c.id;select.append(o)}if(!select.children.length){const o=el('option','','Midknight');o.value='';select.append(o)}label.append(select);options.append(label);
 const levLabel=el('label','','Choose a level');const levels=el('select');levels.id='lm-level';for(let n=1;n<=30;n++){const o=el('option','',`${n} · ${chapters[Math.floor((n-1)/10)]}${state().done[n]?' · kept':''}`);o.value=n;levels.append(o)}levels.value=round?.level||Math.min(30,Object.keys(state().done).length+1);levLabel.append(levels);options.append(levLabel);dlg.append(options);
 dlg.append(el('p','lm-note','All levels are available for this GitHub playtest. Your completed levels stay saved. No timer, currency cost, or lives.'));
 const f=el('fieldset','lm-favours');f.append(el('legend','','Choose one free favour'));for(const [key,[title,desc]]of Object.entries(favours)){const l=el('label');const input=el('input');input.type='radio';input.name='lm-favour';input.value=key;input.checked=key===(round?.favour||'peek');l.append(input,el('strong','',title),el('small','',desc));f.append(l)}dlg.append(f);
 const acts=el('div','lm-actions');if(round&&!round.finished)acts.append(button('Keep playing',play,true));acts.append(button(round&&!round.finished?'Play this level':'Let’s play',()=>{if(round&&!round.finished){const confirm=el('div','lm-confirm');confirm.append(el('p','','Start a new round? Your unfinished board will be replaced. Completed levels stay kept.'),button('Keep playing',home),button('Start fresh',()=>start(+levels.value,dlg.querySelector('[name=lm-favour]:checked').value,select.value),true));acts.replaceChildren(confirm)}else start(+levels.value,dlg.querySelector('[name=lm-favour]:checked').value,select.value)},!round||round.finished));dlg.append(acts);}
function nook(){const s=el('div','lm-nook '+state().tone);const rug=el('div','lm-rug');s.append(rug);const cat=companion();const ci=el('img','lm-companion');ci.src=cat.image||catalog['cat:midknight'].image;ci.alt=cat.name;s.append(ci);
 const chapter=Math.floor((round.level-1)/10);const permanent=state().done[30]?['bed','flowers','lantern']:state().done[20]?['bed','flowers']:state().done[10]?['bed']:[];const found=[...new Set(round.matched.map(i=>round.deck[i]))];const earned=found.filter(k=>k.startsWith('obj:')).map(k=>k.slice(4));if(found.length&&chapter===0)earned.push('bed');const objects=[...new Set([...permanent,...earned])].slice(0,4);for(const [i,key]of objects.entries()){const ob=img('obj:'+key,'lm-nook-item lm-item-'+i);s.append(ob)}return s}
function play(){clear();dlg.replaceChildren();const top=el('div','lm-top');top.append(button('Levels',home),el('span','',`Level ${round.level} / 30`),button('Back to Cove',close));dlg.append(top);const layout=el('div','lm-layout');const side=el('aside','lm-side');side.append(el('h2','',chapters[Math.floor((round.level-1)/10)]),nook(),el('p','lm-speech',`${companion().name} saved you a spot.`));side.querySelector('.lm-speech').setAttribute('role','status');side.querySelector('.lm-speech').setAttribute('aria-live','polite');side.append(el('p','lm-note','Pairs fill this little scene. Chapter keepsakes make part of it stay.'));
 if(state().done[10]){const tones=el('div','lm-actions');for(const tone of ['sage','rose']){const b=button(tone==='sage'?'Sage cushion':'Rose cushion',()=>{state().tone=tone;persist();refreshNook()});b.setAttribute('aria-pressed',state().tone===tone);tones.append(b)}side.append(tones)}
 const main=el('section','lm-main');main.append(el('div','lm-stats'),el('div','lm-board'));const actions=el('div','lm-actions');const favour=button(favours[round.favour][0],useFavour);favour.id='lm-use';actions.append(favour);main.append(actions,el('p','lm-hint',favours[round.favour][1]+' No penalty for a helping paw.'));layout.append(side,main);dlg.append(layout);renderBoard();if(round.finished)finishView();}
function refreshNook(){const old=dlg.querySelector('.lm-nook');if(old)old.replaceWith(nook());const c=dlg.querySelector('.lm-companion');if(c&&!reduced()){c.classList.add('lm-wiggle');c.addEventListener('animationend',()=>c.classList.remove('lm-wiggle'),{once:true})}}
function renderBoard(){const board=dlg.querySelector('.lm-board');if(!board)return;const focusIndex=document.activeElement?.dataset?.card;board.replaceChildren();board.style.setProperty('--cols',round.deck.length===6?3:4);round.deck.forEach((key,i)=>{const matched=round.matched.includes(i),open=matched||i===first||revealed.includes(i)||picks.includes(i);const card=button('',()=>flip(i));card.className='lm-card'+(open?' lm-open':'')+(matched?' lm-matched':'');card.dataset.card=i;card.disabled=matched||busy||round.finished;card.setAttribute('aria-label',open?catalog[key].name+(matched?', matched':''):`Face-down card ${i+1}`);if(open){card.append(img(key,''),el('span','',catalog[key].name));if(matched)card.append(el('b','lm-check','✓'))}else{const back=el('span','lm-card-back');back.innerHTML='<svg viewBox="0 0 48 48" aria-hidden="true"><path d="M12 23 11 10l11 7h6l9-7 0 14q2 15-13 15T12 23Z"/><path d="M17 27q3 4 5 0m6 0q3 4 5 0m-10 6 2 2 2-2"/></svg>';card.append(back)}board.append(card)});dlg.querySelector('.lm-stats').textContent=`${round.matched.length/2} / ${round.deck.length/2} pairs · ${round.turns} turns · No rush`;const f=dlg.querySelector('#lm-use');f.disabled=round.used||busy||round.finished;f.textContent=round.used?'Favour used':picking?'Choose four cards':favours[round.favour][0];if(focusIndex!==undefined)board.querySelector(`[data-card="${focusIndex}"]`)?.focus({preventScroll:true});}
function flip(i){if(busy||round.finished||round.matched.includes(i))return;
 if(picking){if(picks.includes(i))return;picks.push(i);renderBoard();const remaining=round.deck.length-round.matched.length;if(picks.length===Math.min(4,remaining)){round.used=true;picking=false;const chosen=picks.slice();picks=[];persist();pauseReveal(chosen,'Four little clues. They will stay right where they are.')}else say(`Choose ${Math.min(4,remaining)-picks.length} more cards.`);return}
 if(i===first)return;if(first===null){first=i;renderBoard();return}const a=first;round.turns++;round.last=[a,i];if(round.deck[a]===round.deck[i]){first=null;matched(a,i)}else{first=null;persist();pauseReveal([a,i],'Not quite. Two little faces to remember.')}}
function matched(a,b){round.matched.push(a,b);persist();renderBoard();refreshNook();const key=round.deck[a],name=companion().name;const lines=key==='obj:food'?[`${name} heard “bowl.” A brief misunderstanding.`, 'A picture of dinner. An ambitious promise.']:key==='obj:bed'?[`${name} is already considering the cushion.`, 'Apparently this one was for them.']:key.startsWith('cat:')?['A familiar face. A very flattering resemblance.',`${name} approves. Quietly, of course.`]:['One more little thing in its place.','This corner is starting to feel like home.'];say(lines[speaker++%lines.length]);if(round.matched.length===round.deck.length)complete();}
function useFavour(){if(round.used||busy||round.finished)return;if(round.favour==='peek'){if(first!==null){say('Finish this pair before choosing your four cards.');return}picking=true;renderBoard();say('Tap four face-down cards for a little look.');return}
 if(round.favour==='friend'){if(first===null){say('Turn over one card first. Then ask for a helping paw.');return}const a=first,b=round.deck.findIndex((key,i)=>key===round.deck[a]&&i!==a&&!round.matched.includes(i));round.used=true;first=null;round.turns++;matched(a,b);return}
 if(first!==null||round.last.length!==2){say('Try a pair first, then ask for a second look.');return}round.used=true;persist();pauseReveal(round.last.slice(),`${companion().name} remembers these two.`);}
function complete(){round.finished=true;const s=state(),firstCompletion=!s.done[round.level];s.done[round.level]={turns:Math.min(s.done[round.level]?.turns||Infinity,round.turns),helped:round.used};persist();if(firstCompletion&&(round.level===1||round.level%10===0))api.keepsake(round.level,companion());finishView()}
function finishView(){dlg.querySelector('.lm-finish')?.remove();const box=el('div','lm-finish');const milestone=round.level%10===0;box.append(el('h3','',milestone?'Another little memory, kept.':'Everyone found a friend.'),el('p','',milestone?['A cushion to call your own. Choose sage or rose on your next page.','A little plant joins your permanent nook.','A warm lantern. A whole little place together.'][round.level/10-1]:`${companion().name} seems quite pleased with this arrangement.`));box.append(button(round.level===30?'Back to levels':'Next level',()=>round.level===30?home():start(round.level+1,round.favour,round.cat),true));dlg.querySelector('.lm-main').append(box);box.querySelector('button').focus({preventScroll:true});renderBoard();}
function open(){roster=api.cats();if(!catalog)catalog=api.catalog();if(!dlg){dlg=el('dialog','lm-dialog');dlg.setAttribute('aria-label','Little Matches');document.body.append(dlg);dlg.addEventListener('cancel',e=>{e.preventDefault();close()});dlg.addEventListener('keydown',e=>e.stopPropagation())}round=state().round||null;if(round&&(!Array.isArray(round.deck)||round.deck.some(k=>!catalog[k])||!Array.isArray(round.matched)))round=null;api.hide();dlg.showModal();home()}
return{open,build};
};
