/* Little Matches — isolated activity state, persisted in the existing Neo save. */
window.createLittleMatches=function(api){
'use strict';
const rewards=api.rewards;
let previewCat=null;
let raf=0,lastFrame=0,lastAction=Date.now(),mood='watching',jumpAt=-10000,walkUntil=0,misses=0,finishTimer=0,activePopup=null;
const chapters=['Familiar Faces','Favourite Things','A Place Together'];
const curve=[3,3,4,3,4,4,3,4,4,4,4,4,5,4,5,5,4,6,5,6,5,6,6,5,6,7,5,7,7,8];
const coatPools=[['ginger','black','white','siamese','calico','rosewater','tuxedo','browntab'],['ginger','white','calico','siamese','tuxedo','russian','cream','rosewater'],['prism','rosewater','van','smoke','lynxpoint','silver','greytab','tuxedo','ginger','white']];
const objKeys=['food','bed','toy','flowers','lantern','birdbath','windmill','bunting'];
const favours={peek:['Little peek','Choose four cards to see briefly.'],friend:['Find a friend','Turn over one card; your cat finds its pair.'],second:['Second look','See your previous two cards again.']};
let roster=[],catalog=null,dlg=null,round=null,first=null,busy=false,picking=false,picks=[],timer=null,epoch=0,revealed=[],speaker=0;
const reduced=()=>matchMedia('(prefers-reduced-motion: reduce)').matches;
const state=()=>{const s=api.state();s.done ||= {};s.tone ||= 'sage';return s};
const persist=()=>{state().round=round;api.save()};
function rng(seed){return()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296}}
function shuffle(a,r){a=a.slice();for(let i=a.length-1;i;i--){const j=Math.floor(r()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function build(n){const r=rng(n*1777+83),ch=Math.floor((n-1)/10),size=curve[n-1];let keys=shuffle(coatPools[ch],r).slice(0,ch===0?size:Math.ceil(size/2)).map(k=>'cat:'+k);if(ch>0)keys.push(...shuffle(objKeys,r).slice(0,size-keys.length).map(k=>'obj:'+k));return shuffle(keys.flatMap(k=>[k,k]),r)}
function el(tag,cls,text){const e=document.createElement(tag);if(cls)e.className=cls;if(text!==undefined)e.textContent=text;return e}
function button(text,fn,primary=false){const b=el('button','lm-btn'+(primary?' lm-primary':''),text);b.type='button';b.onclick=fn;return b}
function img(key,cls){const i=el('img',cls);i.src=catalog[key].image;i.alt='';return i}
function companion(){return roster.find(c=>c.id===(previewCat||round?.cat))||roster[0]||{name:'Your companion',key:'midknight'}}
function say(text){const t=dlg.querySelector('.lm-speech');if(t)t.textContent=text}
function clear(){cancelAnimationFrame(raf);raf=0;clearTimeout(finishTimer);finishTimer=0;activePopup?.close();activePopup?.remove();activePopup=null;if(round?.shufflePending)openingShuffle();epoch++;clearTimeout(timer);timer=null;busy=false;picking=false;picks=[];revealed=[];first=null}
function close(){clear();persist();dlg.close()}
function pauseReveal(indices,message){busy=true;revealed=indices;renderBoard();say(message);const e=epoch;timer=setTimeout(()=>{if(e!==epoch)return;revealed=[];busy=false;renderBoard();persist()},2200)}
function start(n,favour,cat){clear();if(!allDone())n=nextLevel();lastAction=Date.now();mood='watching';misses=0;round={level:n,deck:build(n),matched:[],turns:0,used:false,favour,cat,last:[],finished:false};persist();play();openingLook();}
function openingShuffle(){
 let order=shuffle(round.deck.map((_,i)=>i),Math.random);
 if(order.every((old,i)=>round.deck[old]===round.deck[i])){const shift=round.deck.findIndex(k=>k!==round.deck[0]);order=round.deck.map((_,i)=>(i+shift)%round.deck.length);}
 round.deck=order.map(i=>round.deck[i]);round.shufflePending=false;persist();return order;
}
function openingLook(){
 busy=true;round.shufflePending=true;persist();revealed=round.deck.map((_,i)=>i);renderBoard();say('Meet this little gathering. A shuffle comes next.');
 const board=dlg.querySelector('.lm-board');if(!reduced())board.classList.add('lm-deal');
 const skip=button('Start now',()=>{if(e!==epoch)return;if(round.shufflePending)openingShuffle();finish();},true);skip.id='lm-start-now';dlg.querySelector('.lm-main .lm-actions').prepend(skip);
 const e=epoch;
 function finish(){if(e!==epoch)return;clearTimeout(timer);timer=null;board.getAnimations({subtree:true}).forEach(a=>a.cancel());revealed=[];busy=false;board.classList.remove('lm-deal');skip.remove();renderBoard();say('Find their friends. Their places stay fixed now.');persist();}
 function mix(){if(e!==epoch)return;revealed=[];board.classList.remove('lm-deal');renderBoard();const old=[...board.children].map(c=>c.getBoundingClientRect());const order=openingShuffle();renderBoard();say('A little shuffle…');
 if(!reduced()){const area=board.getBoundingClientRect();[...board.children].forEach((card,i)=>{const to=card.getBoundingClientRect(),from=old[order[i]],cx=area.left+area.width/2-to.left-to.width/2,cy=area.top+area.height/2-to.top-to.height/2;card.style.zIndex=i+1;card.animate([{transform:'translate('+(from.x-to.x)+'px,'+(from.y-to.y)+'px)'},{transform:'translate('+cx+'px,'+cy+'px) rotate('+(i%2?8:-8)+'deg) scale(.88)',offset:.45},{transform:'translate(0,0) rotate(0) scale(1)'}],{duration:1600,easing:'ease-in-out'});});}
 timer=setTimeout(finish,reduced()?350:1700);
 }
 timer=setTimeout(mix,3000);
}
function nextLevel(){for(let n=1;n<=30;n++)if(!state().done[n])return n;return 30}
function allDone(){return Array.from({length:30},(_,i)=>i+1).every(n=>state().done[n])}
function home(){clear();dlg.replaceChildren();const top=el('div','lm-top');top.append(el('div','lm-kicker','LITTLE MATCHES · 30 LEVELS'),button('Back to Cove',close));dlg.append(top,el('h2','','Little Matches'),el('p','lm-intro','Familiar faces. Favourite things. Your favourite company.'));
 const options=el('div','lm-setup'),label=el('label','','Keep me company'),select=el('select');select.id='lm-cat';for(const c of roster){const o=el('option','',c.name);o.value=c.id;select.append(o)}if(!select.children.length){const o=el('option','','Your companion');o.value='';select.append(o)}select.value=round?.cat||roster[0]?.id||'';previewCat=select.value;select.onchange=()=>{previewCat=select.value};label.append(select);options.append(label);
 let levels=null;if(allDone()){const l=el('label','','Replay a level');levels=el('select');levels.id='lm-level';for(let n=1;n<=30;n++){const o=el('option','','Level '+n);o.value=n;levels.append(o)}l.append(levels);options.append(l)}dlg.append(options);
 dlg.append(el('p','lm-note',allDone()?'All 30 levels complete. Every level is yours to revisit.':'Complete each level to continue. Earn an accessory every five levels. No timer, lives, or entry cost.'));
 const spent=!!(round&&!round.finished&&round.used);const f=el('fieldset','lm-favours');f.disabled=spent;f.append(el('legend','',spent?'Favour used for this level':'Choose one free favour'));if(spent)dlg.append(el('p','lm-note','Your next level comes with a fresh favour.'));for(const [key,[title,desc]]of Object.entries(favours)){const l=el('label');const input=el('input');input.type='radio';input.name='lm-favour';input.value=key;input.checked=key===(round?.favour||'peek');l.classList.toggle('lm-selected',input.checked);input.onchange=()=>f.querySelectorAll('label').forEach(x=>x.classList.toggle('lm-selected',x.querySelector('input').checked));l.append(input,el('strong','',title),el('small','',desc));f.append(l)}dlg.append(f);
 const acts=el('div','lm-actions');if(round&&!round.finished){acts.append(button('Continue · Level '+round.level,()=>{round.cat=select.value;persist();if(!round.used){round.favour=f.querySelector('input:checked').value;persist()}play()},true))}else acts.append(button(allDone()?'Play again':'Continue · Level '+nextLevel(),()=>start(levels?+levels.value:nextLevel(),f.querySelector('input:checked').value,select.value),true));acts.append(button('View rewards',showRewards));dlg.append(acts);
}
function nook(){const c=el('canvas','lm-companion');c.width=300;c.height=270;c.setAttribute('role','img');c.setAttribute('aria-label',companion().name+' keeping you company');return c}
function play(){clear();previewCat=null;lastAction=Date.now();mood='watching';dlg.replaceChildren();const top=el('div','lm-top');top.append(button('Back',home),el('span','', 'Level '+round.level+' / 30'),button('Back to Cove',close));dlg.append(top);const layout=el('div','lm-layout'),side=el('aside','lm-side');side.append(nook(),el('p','lm-speech',companion().name+' is keeping you company.'));side.querySelector('.lm-speech').setAttribute('role','status');side.querySelector('.lm-speech').setAttribute('aria-live','polite');const main=el('section','lm-main');main.append(el('div','lm-stats'),el('div','lm-board'));const actions=el('div','lm-actions'),favour=button(favours[round.favour][0],useFavour);favour.id='lm-use';actions.append(favour);main.append(actions,el('p','lm-hint',favours[round.favour][1]+' No penalty for a helping paw.'));layout.append(side,main);dlg.append(layout);dlg.append(el('section','lm-trail'));renderBoard();renderTrail();animateCat();if(round.finished)finishView();}
function touch(){lastAction=Date.now();mood='watching'}
function refreshNook(){touch();jumpAt=performance.now()}
function animateCat(now=performance.now()){if(!dlg.open)return;if(!document.hidden&&now-lastFrame>32){lastFrame=now;const idle=Date.now()-lastAction;if(!round.finished&&!busy){if(idle>16000)mood='sleep';else if(idle>8000)mood='groom'}const cv=dlg.querySelector('.lm-companion');const jump=(now-jumpAt)/700;if(cv)api.draw(cv,companion(),mood,reduced()?0:jump>0&&jump<1?jump:0,false);const marker=dlg.querySelector('.lm-walker');if(marker)api.draw(marker,companion(),'watching',0,!reduced()&&now<walkUntil)}raf=requestAnimationFrame(animateCat)}
function renderBoard(){const board=dlg.querySelector('.lm-board');if(!board)return;const focusIndex=document.activeElement?.dataset?.card;board.replaceChildren();board.style.setProperty('--cols',round.deck.length===6?3:4);round.deck.forEach((key,i)=>{const matched=round.matched.includes(i),open=matched||i===first||revealed.includes(i)||picks.includes(i);const card=button('',()=>flip(i));card.className='lm-card'+(open?' lm-open':'')+(matched?' lm-matched':'');card.dataset.card=i;card.disabled=matched||busy||round.finished;card.setAttribute('aria-label',open?catalog[key].name+(matched?', matched':''):`Face-down card ${i+1}`);if(open){card.append(img(key,''),el('span','',catalog[key].name));if(matched)card.append(el('b','lm-check','✓'))}else{const back=el('span','lm-card-back');back.innerHTML='<svg viewBox="0 0 48 48" aria-hidden="true"><path d="M12 23 11 10l11 7h6l9-7 0 14q2 15-13 15T12 23Z"/><path d="M17 27q3 4 5 0m6 0q3 4 5 0m-10 6 2 2 2-2"/></svg>';card.append(back)}board.append(card)});dlg.querySelector('.lm-stats').textContent=`${round.matched.length/2} / ${round.deck.length/2} pairs · ${round.turns} turns · No rush`;const f=dlg.querySelector('#lm-use');f.disabled=round.used||busy||round.finished;f.textContent=round.used?'Favour used':picking?'Choose four cards':favours[round.favour][0];if(focusIndex!==undefined)board.querySelector(`[data-card="${focusIndex}"]`)?.focus({preventScroll:true});}
function flip(i){if(busy||round.finished||round.matched.includes(i))return;
 touch();if(picking){if(picks.includes(i))return;if(!round.used){round.used=true;persist()}picks.push(i);renderBoard();const remaining=round.deck.length-round.matched.length;if(picks.length===Math.min(4,remaining)){round.used=true;picking=false;const chosen=picks.slice();picks=[];persist();pauseReveal(chosen,'Four little clues. They will stay right where they are.')}else say(`Choose ${Math.min(4,remaining)-picks.length} more cards.`);return}
 if(i===first)return;if(first===null){first=i;renderBoard();return}const a=first;round.turns++;round.last=[a,i];if(round.deck[a]===round.deck[i]){first=null;matched(a,i)}else{first=null;misses++;if(misses>=2)mood='groom';persist();pauseReveal([a,i],'Not quite. Two little faces to remember.')}}
function matched(a,b){misses=0;round.matched.push(a,b);persist();renderBoard();refreshNook();const key=round.deck[a],name=companion().name;const lines=key==='obj:food'?[`${name} heard “bowl.” A brief misunderstanding.`, 'A picture of dinner. An ambitious promise.']:key==='obj:bed'?[`${name} is already considering the cushion.`, 'Apparently this one was for them.']:key.startsWith('cat:')?['A familiar face. A very flattering resemblance.',`${name} approves. Quietly, of course.`]:['Found them. A small hop felt appropriate.','A very good match. A very pleased cat.'];say(lines[speaker++%lines.length]);if(round.matched.length===round.deck.length)complete();}
function useFavour(){if(round.used||busy||round.finished)return;if(round.favour==='peek'){if(first!==null){say('Finish this pair before choosing your four cards.');return}picking=true;renderBoard();say('Tap four face-down cards for a little look.');return}
 if(round.favour==='friend'){if(first===null){say('Turn over one card first. Then ask for a helping paw.');return}const a=first,b=round.deck.findIndex((key,i)=>key===round.deck[a]&&i!==a&&!round.matched.includes(i));round.used=true;first=null;round.turns++;matched(a,b);return}
 if(first!==null||round.last.length!==2||round.last.some(i=>round.matched.includes(i))){say('Try an unmatched pair first, then ask for a second look.');return}round.used=true;persist();pauseReveal(round.last.slice(),`${companion().name} remembers these two.`);}
function complete(){round.finished=true;const s=state(),previous=s.done[round.level],firstCompletion=!previous;if(!previous||round.turns<previous.turns)s.done[round.level]={turns:round.turns,helped:round.used};persist();if(firstCompletion&&(round.level===1||round.level%5===0))api.keepsake(round.level,companion());walkUntil=performance.now()+850;renderTrail(true);finishTimer=setTimeout(()=>{finishTimer=0;if(dlg.open){if(firstCompletion&&(allDone()||rewards.some(r=>r.level===round.level)))showReward(allDone()?rewards[5]:rewards.find(r=>r.level===round.level),true);else finishView()}},reduced()?0:950)}
function finishView(){
 dlg.querySelector('.lm-finish')?.remove();
 const box=popup('Level '+round.level+' complete'),done=state().done,finished=allDone(),name=companion().name;box.classList.add('lm-completion');
 const quips=[name+' did the victory hop. You did the remembering.',name+' is taking the credit. We both know who turned the cards.',name+' checked under a paw. No missing matches.',name+' has postponed the nap. This is getting interesting.',name+' would high-five you, but that paw was just washed.',name+' celebrated with a tiny hop. Very big feelings.'];
 box.append(el('h2','',finished?'Small paws. A mighty finish.':'Level '+round.level+' complete!'),el('p','',finished?'Watch out for the next drop next season.':quips[(round.level-1)%quips.length]));
 if(!finished){
  const next=rewards.find(r=>!done[r.level]);
  if(next){
   const remaining=Array.from({length:next.level},(_,i)=>i+1).filter(n=>!done[n]).length;
   const preview=button('',()=>showReward(next));preview.className='lm-next-reward';
   const copy=el('span');copy.append(el('strong','',remaining===1?'One more level to earn your '+next.label+'!':remaining+' levels to your '+next.label),el('span','','Level '+next.level+' reward · Tap to try it on'));
   preview.append(rewardArt(next),copy);box.append(preview);
  }else{
   const remaining=Array.from({length:30},(_,i)=>i+1).filter(n=>!done[n]).length;
   box.append(el('p','lm-season',remaining+' level'+(remaining===1?'':'s')+' left to finish all 30 and unlock free replay.'));
  }
 }
 const actions=el('div','lm-actions');
 actions.append(button(finished?'Replay a level':'Play Level '+nextLevel(),()=>finished?home():start(nextLevel(),round.favour,round.cat),true));
 actions.append(button('View rewards',showRewards));box.append(actions,button('Back to Cove',close));renderBoard();actions.querySelector('button')?.focus({preventScroll:true});
}
function rewardArt(r){const image=el('img');image.src=api.rewardImage(companion(),r.key);image.alt=companion().name+' wearing '+r.label;return image}
function renderTrail(animate=false){const trail=dlg.querySelector('.lm-trail');if(!trail)return;const old=trail.querySelector('.lm-walker'),from=old?parseFloat(old.style.left):null;trail.replaceChildren();const level=round.level,target=Math.ceil(level/5)*5,start=target-5,r=rewards.find(r=>r.level===target),done=state().done;let count=0;for(let n=start+1;n<=target;n++)if(done[n])count++;const head=el('div','lm-trail-head');head.append(el('span','',r.label+(count===5?' · Earned':' · '+(5-count)+' level'+(5-count===1?'':'s')+' to go')),button('View rewards',showRewards));trail.append(head);const track=el('div','lm-track'),line=el('div','lm-trail-line'),fill=el('div','lm-trail-fill');fill.style.width=count*20+'%';line.append(fill);track.append(line);const walker=el('canvas','lm-walker');walker.width=100;walker.height=95;walker.style.left=count*20+'%';walker.setAttribute('aria-label','Progress: '+count+' of 5 levels');track.append(walker);for(let i=0;i<=5;i++){const mark=el('span','lm-trail-mark'+(i===0||done[start+i]?' lm-earned':''));mark.style.left=i*20+'%';mark.append(el('i'),el('span','',String(start+i||'Start')));track.append(mark)}const reward=button('',()=>showReward(r));reward.className='lm-trail-reward';reward.setAttribute('aria-label','Preview '+r.label);reward.append(rewardArt(r));track.append(reward);trail.append(track);api.draw(walker,companion(),'watching',0,false);
 if(animate&&!reduced()&&from!==null&&from<count*20){
  walker.style.left=from+'%';fill.style.width=from+'%';
  track.getBoundingClientRect();
  walker.style.left=count*20+'%';fill.style.width=count*20+'%';
 }
}
function popup(title){activePopup?.close();activePopup?.remove();const p=el('dialog','lm-popup');p.setAttribute('aria-label',title);p.addEventListener('keydown',e=>e.stopPropagation());p.addEventListener('cancel',e=>{e.preventDefault();dismiss()});dlg.append(p);activePopup=p;p.showModal();return p}
function dismiss(){const completion=activePopup?.classList.contains('lm-completion');activePopup?.close();activePopup?.remove();activePopup=null;if(completion){home();return}if(round?.finished&&dlg.querySelector('.lm-main')){finishView();return}dlg.querySelector('.lm-trail-head button,.lm-actions button')?.focus()}
function showRewards(){const p=popup('Accessory rewards');p.append(button('Close',dismiss),el('h2','','A little something to wear'),el('p','lm-note','An accessory every five levels. Yours to keep, for all your cats.'));const grid=el('div','lm-reward-grid');for(const r of rewards){const b=button('',()=>showReward(r));b.append(rewardArt(r),el('strong','',r.label),el('span','', 'Level '+r.level+' · '+(state().done[r.level]?'Earned':'Locked')));grid.append(b)}p.append(grid)}
function showReward(r,celebrate=false){const earned=!!state().done[r.level],final=celebrate&&allDone(),p=popup(r.label);p.classList.toggle('lm-unlock',celebrate&&!reduced());p.append(el('div','lm-kicker',final?'ALL 30 LEVELS COMPLETE':'LEVEL '+r.level+(earned?' · EARNED':' · REWARD')),el('h2','',final?'Small paws. A mighty finish.':celebrate?'A little something, earned.':r.label),rewardArt(r));if(celebrate){p.append(el('h3','',r.label+' unlocked'),el('p','',final?'Congratulations! You and '+companion().name+' matched your way through all 30 levels. The mane is magnificent. The roar needs practice.':companion().name+' helped. Mostly by looking adorable. Your new accessory is ready to wear.'));if(final)p.append(el('p','lm-season','Watch out for the next drop next season.'),el('p','lm-note','For now, every level is yours to revisit.'));if(!reduced()){const sparks=el('div','lm-sparks');sparks.setAttribute('aria-hidden','true');for(let i=0;i<8;i++){const star=el('span','','✦');star.style.setProperty('--x',Math.cos(i*Math.PI/4)*125+'px');star.style.setProperty('--y',Math.sin(i*Math.PI/4)*100+'px');sparks.append(star)}p.append(sparks)}}else p.append(el('p','',earned?'Ready for a little dress-up.':'Complete Level '+r.level+' to make it yours.'));const acts=el('div','lm-actions');if(earned){const wear=button('Wear it',()=>{if(api.wear(companion(),r.key)){wear.textContent='Wearing it ✓';wear.disabled=true}else{p.querySelector('.lm-wear-note')?.remove();p.append(el('p','lm-note lm-wear-note','Your companion is away. This reward is safe in Dress-up for your resident cats.'))}},true);acts.append(wear)}acts.append(button(celebrate?(final?'Replay a level':'Play Level '+nextLevel()):'Back',()=>{dismiss();if(celebrate){if(allDone())home();else start(nextLevel(),round.favour,round.cat)}},!earned));p.append(acts);acts.querySelector('button')?.focus()}
function open(){roster=api.cats();if(!catalog)catalog=api.catalog();if(!dlg){dlg=el('dialog','lm-dialog');dlg.setAttribute('aria-label','Little Matches');document.body.append(dlg);dlg.addEventListener('cancel',e=>{e.preventDefault();close()});dlg.addEventListener('keydown',e=>e.stopPropagation())}round=state().round||null;if(round&&(!Array.isArray(round.deck)||round.deck.some(k=>!catalog[k])||!Array.isArray(round.matched)))round=null;api.hide();dlg.showModal();for(const r of rewards)if(state().done[r.level])api.keepsake(r.level,companion());home()}
return{open,build};
};
