/* Use packaged artwork for interface symbols rather than OS emoji fonts. */
(()=>{'use strict';
const icons={'🐾':['paw','Cat'],'🐈':['catdex','Cat'],'🐱':['catdex','Cat'],'🏠':['homecoming','Cove'],'🏡':['homecoming','Cove'],'🏆':['trophy','Trophy'],'🎒':['adventure','Adventure'],'🌙':['rest','Rest'],'🔒':['lock','Locked'],'📷':['photo','Photo'],'📸':['photo','Photo'],'🎣':['dest-fishing','Fishing'],'🌻':['garden','Garden'],'🌱':['garden','Garden'],'🛒':['shop','Shop'],'🛍️':['shop','Shop'],'📖':['journal','Journal'],'🎉':['festival','Celebration'],'🏁':['race','Race'],'🔊':['sound','Sound'],'🔇':['muted','Muted'],'🍽':['pantry','Food'],'🍽️':['pantry','Food'],'❤️':['heart','Love'],'❤':['heart','Love'],'💧':['water','Water'],'✉️':['letter','Postcard'],'🗿':['cairn','Cairn']};
const shapes={heart:'M12 20S3 14 3 8a5 5 0 0 1 9-3 5 5 0 0 1 9 3c0 6-9 12-9 12Z',water:'M12 3S5 11 5 15a7 7 0 0 0 14 0c0-4-7-12-7-12Z',letter:'M3 5h18v14H3ZM3 5l9 8 9-8',cairn:'M4 20h16l-2-4H6ZM7 14h10l-2-4H9ZM10 8h4l-1-4h-2Z'};
const pattern=new RegExp(Object.keys(icons).sort((a,b)=>b.length-a.length).join('|'),'gu');
function scan(root){const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);const nodes=[];while(walker.nextNode())nodes.push(walker.currentNode);for(const node of nodes){if(!node.parentElement||node.parentElement.closest('script,style,textarea,input,select,svg,[contenteditable],.platform-icon'))continue;pattern.lastIndex=0;if(!pattern.test(node.data))continue;pattern.lastIndex=0;const out=document.createDocumentFragment();let end=0;for(const match of node.data.matchAll(pattern)){out.append(node.data.slice(end,match.index));const [key,label]=icons[match[0]],wrap=document.createElement('span');wrap.className='platform-icon';wrap.setAttribute('role','img');wrap.setAttribute('aria-label',label);wrap.innerHTML=shapes[key]?'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linejoin="round"><path d="'+shapes[key]+'"/></svg>':'<img src="art/icon-keepsake-'+key+'.svg" alt="">';out.append(wrap);end=match.index+match[0].length}out.append(node.data.slice(end));node.replaceWith(out)}}
const pending=new Set();let scheduled=false;const observer=new MutationObserver(records=>{for(const r of records){if(r.type==='characterData')pending.add(r.target.parentElement);else for(const n of r.addedNodes)if(n.nodeType===1||n.nodeType===3)pending.add(n.nodeType===3?n.parentElement:n)}if(!scheduled){scheduled=true;requestAnimationFrame(()=>{scheduled=false;observer.disconnect();for(const n of pending)if(n?.isConnected&&!n.closest('.platform-icon'))scan(n);pending.clear();watch()})}});
function watch(){observer.observe(document.body,{subtree:true,childList:true,characterData:true})}scan(document.body);watch();
})();
